#!/bin/bash

# Jamie Luck's Herbstluftwm config file
# Started on July 4, 2013. MURRICA

function hc() {
    herbstclient "$@"
}

# get color variables from xres
source ~/.colors

hc emit_hook reload

# background
#xsetroot -solid '#e8e9ca'

# remove all existing keybindings
hc keyunbind --all

# Keybindings
mod=Mod1
mod4=Mod4

hc keybind $mod-Shift-e quit
hc keybind $mod-Shift-r reload
hc keybind $mod4-Shift-e spawn killall wmswap

# Close a window
hc keybind $mod-Shift-q close

# program launchers
hc keybind $mod-t spawn urxvt
hc keybind $mod4-Shift-b spawn ~/scripts/miscWall.sh
hc keybind $mod4-Shift-v spawn ~/scripts/dmenu_wallpaper
hc keybind $mod4-t spawn ~/scripts/browserswap

# Special Keys
hc keybind XF86KbdBrightnessUp spawn asus-kbd-backlight up
hc keybind XF86KbdBrightnessDown spawn asus-kbd-backlight down
hc keybind XF86TouchpadToggle spawn ~/scripts/touchpadtoggle
hc keybind XF86WebCam spawn scrot -q 100 '%Y-%m-%d_%H-%M-%S_$wx$h.png' -e 'mv $f ~/pictures/screenshot'
hc keybind XF86AudioRaiseVolume spawn ~/scripts/dvol -i 5
hc keybind XF86AudioLowerVolume spawn ~/scripts/dvol -d 5
hc keybind XF86AudioMute spawn ~/scripts/dvol -t
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86AudioNext spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev
hc keybind XF86AudioStop spawn mpc stop
hc keybind XF86Calculator spawn ~/scripts/dmenu_calc
hc keybind XF86Launch1 spawn mplayer tv://
# hc keybind XF86Launch6

# Mod+Fx
hc keybind $mod-F1 spawn ~/scripts/dmenu_man
hc keybind $mod-F2 spawn ~/scripts/dmenu_run_enhanced
hc keybind $mod-F3 spawn ~/scripts/dmenu_openwith
hc keybind $mod-F4 spawn ~/scripts/dmenu_nmcli
hc keybind $mod-F5 spawn ~/scripts/rscontrol -i
hc keybind $mod-F6 spawn ~/scripts/rscontrol -d
# hc keybind $mod-F7 spawn ~/scripts/
# hc keybind $mod-F8 spawn ~/scripts/
hc keybind $mod-F9 cycle_value window_border_width 0 1 2 5
# hc keybind $mod-F9 spawn ~/scripts/
hc keybind $mod-F10 spawn amixer set Speaker toggle
# hc keybind $mod-F11 spawn ~/scripts/
hc keybind $mod-F11 cycle_value frame_padding 0 5 20
# hc keybind $mod-F12 spawn ~/scripts/
hc keybind $mod-F12 cycle_value window_border_active_color $COLOR0 $COLOR1 $COLOR2 $COLOR3 $COLOR4 $COLOR5 $COLOR6 $COLOR7 $COLOR8 $COLOR9 

# tags
TAG_NAMES=( a s d f g )
TAG_KEYS=( a s d f g )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $mod-w use_index +1 --skip-visible
hc keybind $mod-b  use_index -1 --skip-visible

# layouting
hc keybind $mod-r remove
hc keybind $mod-space chain , lock , rotate , unlock
hc keybind $mod-Shift-space cycle_layout 1
hc keybind $mod-u split vertical 0.5
hc keybind $mod-o split horizontal 0.5
hc keybind $mod-m floating toggle
hc keybind $mod-apostrophe fullscreen toggle
hc keybind $mod-p pseudotile toggle

# Dominant window on right, two split on left
hc keybind $mod-Shift-o load '(split horizontal:0.500000:0 (split vertical:0.500000:1 (clients vertical:0 0x80000b) (clients vertical:0 0xc0000b)) (clients vertical:0 0x100000b))'
# Dominant window on bottom, two split on top
hc keybind $mod-Shift-u load '(split vertical:0.500000:0 (split horizontal:0.500000:0 (clients vertical:0 0xc0000b) (clients vertical:0 0x100000b)) (clients vertical:0 0x80000b))'
hc keybind $mod-Shift-i load '(split horizontal:0.650000:0 (clients vertical:0 0x140000b) (split vertical:0.200000:1 (clients vertical:0 0x100000b) (clients vertical:0 0xa0000b)))'
hc keybind $mod-Shift-y load '(split horizontal:0.750000:0 (split vertical:0.700000:0 (clients vertical:0 0x80000b) (clients vertical:0 0xa0000b)) (clients vertical:0 0x100000b))'


hc keybind $mod-i chain , split vertical 0.7 , shift_edge u , split vertical 0.7

# resizing
RESIZESTEP=0.05
SMALLERRESIZESTEP=0.025
hc keybind $mod-Control-h resize left +$RESIZESTEP
hc keybind $mod-Control-j resize down +$RESIZESTEP
hc keybind $mod-Control-k resize up +$RESIZESTEP
hc keybind $mod-Control-l resize right +$RESIZESTEP

hc keybind $mod-Control-Shift-h resize left +$SMALLERRESIZESTEP
hc keybind $mod-Control-Shift-j resize down +$SMALLERRESIZESTEP
hc keybind $mod-Control-Shift-k resize up +$SMALLERRESIZESTEP
hc keybind $mod-Control-Shift-l resize right +$SMALLERRESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $mod-Button1 spawn ~/scripts/dvol -i 5
# hc mousebind $mod-Button2 resize
# hc mousebind $mod-Button3 zoom

# focus
# hc keybind $mod-BackSpace   cycle_monitor
hc keybind $mod-Tab         cycle_all +1
hc keybind $mod-Shift-Tab   cycle_all -1
hc keybind $mod-c cycle
hc keybind $mod-h focus left
hc keybind $mod-j focus down
hc keybind $mod-k focus up
hc keybind $mod-l focus right
#hc keybind $mod-i jumpto urgent
hc keybind $mod-Shift-h shift left
hc keybind $mod-Shift-j shift down
hc keybind $mod-Shift-k shift up
hc keybind $mod-Shift-l shift right

# hc keybind $mod-F11 set frame_padding 5
# hc keybind $mod-F12 set frame_padding 20


# Frames
hc set frame_border_normal_color $COLOR16
hc set frame_border_active_color $COLOR0
hc set frame_border_width 0

hc set frame_bg_normal_color $COLOR16
hc set frame_bg_active_color $COLOR16
hc set frame_bg_transparent 1

# hc set frame_border_inner_color
# hc set frame_border_inner_width

# Windows
hc set window_border_active_color $COLOR4
hc set window_border_normal_color $COLOR9
hc set window_border_urgent_color $rd
hc set window_border_inner_width 0
# hc set window_border_inner_color $COLOR16
hc set window_border_width 1

hc set always_show_frame 0
hc set frame_gap 0
hc set window_gap 0
hc set frame_padding 20

# hc set always_show_frame 
# hc set default_frame_layout 
# hc set focus_stealing_prevention 
# hc set frame_active_opacity 100 # Makes the current frame opaque!
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0
hc set raise_in_click 0

# rules
hc unrule -F
hc rule focus=off # normally do not focus new clients

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule class=Firefox tag=s
hc rule class=Opera tag=s
hc rule class=Steam tag=g
hc rule class=Lxappearance pseudotile=on

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

# herbstclient set tree_style '╾│ ├└╼─┐'
herbstclient set tree_style ''

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

# and autostart
# hc spawn compton &
# hc spawn mpd &
# hc spawn dropbox start &
#hc spawn sh ~/.fehbg &
hc spawn xsetroot -solid #262626 
hc spawn unclutter -idle 1 -root
