#!/bin/bash

# File to be sourced COLOR4enever dmenu is run.
source ~/.colors # Get the colors we'll need from the theme

DMENU="dmenu -i -h 13 -nb $COLOR16 -nf $COLOR9 -sb $COLOR16 -sf $COLOR17 -fn gohufont"
DMENUR="dmenu_run -i -h 13 -nb $COLOR16 -nf $COLOR9 -sb $COLOR16 -sf $COLOR17 -fn gohufont"
