---
- name: install dotfiles
  git: repo=https://github.com/delucks/dotfiles dest=~/dotfiles update=yes
- name: install scripts
  git: repo=https://github.com/delucks/scripts dest=~/scripts update=yes
- name: install zsh-syntax-highlighting
  git: repo=https://github.com/zsh-users/zsh-syntax-highlighting dest=~/.zsh-syntax-highlighting update=yes
- name: install colorman
  git: repo=https://github.com/delucks/colorman dest=~/colorman update=yes
- name: create ranger directory
  file: path=~/.config/ranger state=directory
- name: create dunst directory
  file: path=~/.config/dunst state=directory
- name: create herbstluftwm directory
  file: path=~/.config/herbstluftwm state=directory
- name: create weechat directory
  file: path=~/.weechat state=directory
- name: copy weechat config
  copy: src=~/dotfiles/.weechat/ dest=~/.weechat
- name: copy dunstrc
  copy: src=~/dotfiles/dunstrc dest=~/.config/dunst/
- name: copy ranger config
  copy: src=~/dotfiles/ranger/ dest=~/.config/ranger/
- name: copy herbstluftwm config
  copy: src=~/dotfiles/herbstluftwm/ dest=~/.config/herbstluftwm/
- name: symlink dotfiles
  file: src=~/dotfiles/{{ item }}
    dest=~/{{item}}
    state=link
    force=yes
  with_items:
    - .abcde.conf
    - .ackrc
    - .aliasrc
    - .bashrc
    - .compton.conf
    - .dmenurc
    - .gdbinit
    - .gitconfig
    - .i3
    - .i3blocks.conf
    - .irssi
    - .ncmpcpp
    - .redshiftgrc
    - .tmux.conf
    - .vim
    - .vimrc
    - .weechat
    - .xinitrc
    - .xmobarrc
    - .Xmodmap
    - .Xresources
    - .zshrc
- name: install vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
