---
- name: Install on FreeBSD
  sudo: yes
  when: ansible_distribution == 'FreeBSD'  
  pkgng: name={{ item }} state=present
  with_items: "{{ software_list }}"
- name: Install on Debian
  sudo: yes
  when: ansible_distribution == 'Debian'  
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ software_list }}"
- name: Install on CentOS
  sudo: yes
  when: ansible_distribution == 'CentOS'  
  yum: name={{ item }} state=latest
  with_items: "{{ software_list }}"
