#!/usr/bin/env bash

#-------------------------------------------------------#
#     __           __       __  __     _____
#    / /  ___ ____/ /  ___ / /_/ /_ __/ _/ /__    ____ _
#   / _ \/ -_) __/ _ \(_-</ __/ / // / _/ __/ |/|/ /  ' \
#  /_//_/\__/_/ /_.__/___/\__/_/\_,_/_/ \__/|__,__/_/_/_/
#
#                          Elegant *nix window management
#
#-------------------------------------------------------#
# Setup

source "$HOME/.config/herbstluftwm/common.sh"

log "Configuring herbstluftwm for $(hostname)"
herbstclient emit_hook reload
herbstclient keyunbind --all

#-------------------------------------------------------#
# Tags

TAG_NAMES=( a s d f g q w e )
TAG_KEYS=( a s d f g q w e )

for i in ${!TAG_NAMES[@]} ; do
    herbstclient add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        herbstclient keybind "$mod-$key" use_index "$i"
        herbstclient keybind "$mod-Shift-$key" move_index "$i"
    fi
done
log "Set up tags"

#-------------------------------------------------------#
# Layouts

# Dominant window on right, two split on left
#herbstclient keybind $mod-Shift-o load '(split horizontal:0.500000:0 (split vertical:0.500000:1 (clients vertical:0 0x80000b) (clients vertical:0 0xc0000b)) (clients vertical:0 0x100000b))'
# Dominant window on bottom, two split on top
#herbstclient keybind $mod-Shift-u load '(split vertical:0.500000:0 (split horizontal:0.500000:0 (clients vertical:0 0xc0000b) (clients vertical:0 0x100000b)) (clients vertical:0 0x80000b))'
#herbstclient keybind $mod-Shift-i load '(split horizontal:0.650000:0 (clients vertical:0 0x140000b) (split vertical:0.200000:1 (clients vertical:0 0x100000b) (clients vertical:0 0xa0000b)))'
#herbstclient keybind $mod-Shift-y load '(split horizontal:0.750000:0 (split vertical:0.700000:0 (clients vertical:0 0x80000b) (clients vertical:0 0xa0000b)) (clients vertical:0 0x100000b))'

#-------------------------------------------------------#
# Keybindings

herbstclient keybind $mod-Shift-Escape quit
herbstclient keybind $mod-Escape reload
herbstclient keybind $mod-Shift-r close
#herbstclient keybind $mod-n spawn ~/scripts/current
#herbstclient keybind $mod-Menu spawn ~/scripts/getwindow

# Basics
herbstclient keybind $mod-h focus left
herbstclient keybind $mod-j focus down
herbstclient keybind $mod-k focus up
herbstclient keybind $mod-l focus right

herbstclient keybind $mod-Shift-h shift left
herbstclient keybind $mod-Shift-j shift down
herbstclient keybind $mod-Shift-k shift up
herbstclient keybind $mod-Shift-l shift right

# Layouting
herbstclient keybind $mod-r remove
herbstclient keybind $mod-space chain , lock , rotate , unlock
herbstclient keybind $mod-Shift-space cycle_layout 1
herbstclient keybind $mod-u split vertical 0.5
herbstclient keybind $mod-Shift-u split vertical 0.25
herbstclient keybind $mod-o split horizontal 0.5
herbstclient keybind $mod-Shift-o split horizontal 0.25
herbstclient keybind $mod-m floating toggle
herbstclient keybind $mod-apostrophe fullscreen toggle
#herbstclient keybind $mod-p pseudotile toggle

log "Layouting commands set"

# Resizing
herbstclient keybind $mod-Control-h resize left +$RESIZESTEP
herbstclient keybind $mod-Control-j resize down +$RESIZESTEP
herbstclient keybind $mod-Control-k resize up +$RESIZESTEP
herbstclient keybind $mod-Control-l resize right +$RESIZESTEP

herbstclient keybind $mod-Control-Shift-h resize left +$SMALLERRESIZESTEP
herbstclient keybind $mod-Control-Shift-j resize down +$SMALLERRESIZESTEP
herbstclient keybind $mod-Control-Shift-k resize up +$SMALLERRESIZESTEP
herbstclient keybind $mod-Control-Shift-l resize right +$SMALLERRESIZESTEP

# Cycle through windows in current tag
herbstclient keybind $mod-Tab         cycle_all +1
herbstclient keybind $mod-Shift-Tab   cycle_all -1

log "Resize/cycle set"

# Program launchers
herbstclient keybind $mod-t spawn urxvt
herbstclient keybind $mod4-t spawn xterm
herbstclient keybind $mod-comma spawn rofi -show run -display-run 'Run: '

# Mod+Fx
#herbstclient keybind $mod-F1 spawn ~/scripts/dmenu_man
#herbstclient keybind $mod-F2 spawn ~/scripts/dmenu_run_enhanced
#herbstclient keybind $mod-F3 spawn ~/scripts/dmenu_ssh
#herbstclient keybind $mod-F4 spawn ~/scripts/
#herbstclient keybind $mod-F5 spawn ~/scripts/
#herbstclient keybind $mod-F6 spawn ~/scripts/
#herbstclient keybind $mod-F7 spawn ~/scripts/
#herbstclient keybind $mod-F8
#herbstclient keybind $mod-F9
#herbstclient keybind $mod-F10 spawn amixer set Speaker toggle
#herbstclient keybind $mod-F11
#herbstclient keybind $mod-F12
#herbstclient keybind $mod-Enter spawn
#herbstclient keybind $mod-Up spawn ~/scripts/dmenu_mpc_selectPlaylist
#herbstclient keybind $mod-Down spawn ~/scripts/dmenu_mpc_selectPlaylist
#herbstclient keybind $mod-Left spawn ~/scripts/dmenu_mpc_selectPlaylist
#herbstclient keybind $mod-Right spawn ~/scripts/dmenu_mpc_selectPlaylist

# Special Keys
herbstclient keybind $mod-F11 spawn /sbin/wsconsctl display.brightness-=5
herbstclient keybind $mod-F12 spawn /sbin/wsconsctl display.brightness+=5
#herbstclient keybind XF86KbdBrightnessUp spawn
#herbstclient keybind XF86KbdBrightnessDown spawn
#herbstclient keybind XF86TouchpadToggle spawn
#herbstclient keybind XF86WebCam spawn
#herbstclient keybind XF86AudioRaiseVolume spawn ~/scripts/dvol -i 5
#herbstclient keybind XF86AudioLowerVolume spawn ~/scripts/dvol -d 5
#herbstclient keybind XF86AudioMute spawn ~/scripts/dvol -t
#herbstclient keybind XF86AudioPlay spawn
#herbstclient keybind XF86AudioNext spawn
#herbstclient keybind XF86AudioPrev spawn
#herbstclient keybind XF86AudioStop spawn
#herbstclient keybind XF86Calculator spawn
#herbstclient keybind XF86Launch1 spawn
#herbstclient keybind XF86Launch6 spawn

log "Program launchers set"

#-------------------------------------------------------#
# Mousebinds

herbstclient mouseunbind --all
herbstclient mousebind $mod-Button1 move
herbstclient mousebind $mod-Shift-Button1 resize
herbstclient mousebind $mod4-Button1 zoom

log "Mousebinds set"

#-------------------------------------------------------#
# Theming

if [[ "$(herbstclient attr theme.active.color)" == "$COLOR9"	]]; then
  log 'Skipping theme re-init, use `bash ~/.config/herbstluftwm/theme.sh` to reload manually'
else
  herbstclient attr theme.reset 1
  bash "$HOME/.config/herbstluftwm/theme.sh"
  log "Theme reset"
fi

#-------------------------------------------------------#
# settings

herbstclient attr settings.frame_padding 0
herbstclient attr settings.snap_gap 10
herbstclient attr settings.snap_distance 30
herbstclient attr settings.always_show_frame 0
herbstclient attr settings.frame_gap 15
herbstclient attr settings.window_gap 0
herbstclient attr settings.update_dragged_clients 1
herbstclient attr settings.smart_window_surroundings 0
herbstclient attr settings.smart_frame_surroundings 1
herbstclient attr settings.mouse_recenter_gap 0
herbstclient attr settings.focus_follows_mouse 0
herbstclient attr settings.raise_on_click 0
#herbstclient attr settings.frame_active_opacity 100
herbstclient attr settings.tree_style '╾│ ├└╼─┐'

log "Settings for frames/windows set"

#-------------------------------------------------------#
# rules

herbstclient unrule -F
herbstclient rule focus=off # normally do not focus new clients

herbstclient rule class=Steam tag=g
herbstclient rule class=Lxappearance pseudotile=on

herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

log "Rules set"

#-------------------------------------------------------#
# multi-monitor

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# herbstclient detect_monitors

#-------------------------------------------------------#
# panel

#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    $panel $monitor &
#done
#herbstclient spawn xmobar &
#herbstclient pad ${1:-0} 0

#-------------------------------------------------------#
# program launch

herbstclient spawn sh ~/.fehbg &

herbstclient unlock

log "Done!"
