---
- hosts: targets
  user: jamie
  sudo: yes
  vars:
    software_list:
      - nginx
  tasks:
    - name: install nginx
      include: tasks/install.yml
    - name: remove old files in html dir
      file: path=/usr/share/nginx/html/ state=absent
    - name: clone my website
      git: repo=https://github.com/delucks/www.jamesluck.com dest=/usr/share/nginx/html/
    - name: restart nginx service
      service: name=nginx state=restarted enabled=yes
